name: Test and Documentation

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Set up Maven
      run: mvn --version

    - name: Run Tests & Generate JaCoCo Report
      run: mvn clean verify jacoco:report

    - name: Archive Surefire Reports
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: surefire-reports
        path: target/surefire-reports/

    - name: Archive JaCoCo Report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: jacoco-report
        path: target/site/jacoco/

    - name: Generate Doxygen Docs
      run: |
        sudo apt-get update
        sudo apt-get install -y doxygen graphviz
        doxygen Doxyfile

    - name: Check Graphviz install
      run: |
        dot -V
        which dot
        echo "DOT path: $(which dot)"

    - name: Archive Doxygen Docs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: doxygen-docs
        path: docs/

    - name: Archive Performance Reports
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: performance-reports
        path: performance-reports/

    - name: Deploy to gh-pages branch
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
    
        COMMIT_HASH=$(git rev-parse --short HEAD)
    
        git fetch origin gh-pages
        git worktree add gh-pages gh-pages
    
        rm -rf gh-pages/*
        mkdir -p gh-pages/docs
        mkdir -p gh-pages/target/reports
        mkdir -p gh-pages/target/site/jacoco
    
        # ✅ Copia fiable de todo, incluidas las gráficas
        rsync -av --delete docs/ gh-pages/docs/
        rsync -av target/reports/ gh-pages/target/reports/
        rsync -av target/site/jacoco/ gh-pages/target/site/jacoco/
    
        cp index.html gh-pages/index.html
        touch gh-pages/.nojekyll
    
        cd gh-pages
        git add .
        git commit -m "Update GitHub Pages with latest dashboard and reports from $COMMIT_HASH"
        git push origin gh-pages



